---

# - name: Get Kubernetes apt-key
#   apt_key:
#    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
#    state: present

# Note: currently the latest repository is still xenial not bionic
# - name: Add Kubernetes APT repository
#   apt_repository:
#    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
#    state: present
#    filename: 'kubernetes'
      
# Install packages
# - name: Install required software
#   apt: 
#     name: "{{ packages }}"
#     update_cache: true
#     state: present
#   vars:
#       packages:
#       - docker.io
#       - kubelet
#       - kubeadm
#       - kubectl

# Docker service is disabled by default
# - name: enable Docker service
#   systemd:
#     name: docker
#     enabled: yes


 - name: Install packages that allow apt to be used over HTTPS
   apt:
     name: "{{ packages }}"
     state: present
     update_cache: yes
   vars:
     packages:
     - apt-transport-https
     - ca-certificates
     - curl
     - gnupg-agent
     - software-properties-common

 - name: Add an apt signing key for Docker
   apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg
     state: present

 - name: Add apt repository for stable version
   apt_repository:
     repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
     state: present

 - name: Install docker and its dependecies
   apt: 
     name: "{{ packages }}"
     state: present
     update_cache: yes
   vars:
     packages:
     - docker-ce 
     - docker-ce-cli 
     - containerd.io

# Docker service is disabled by default
 - name: enable Docker service
   systemd:
     name: docker
     enabled: yes

 - name: Add user to docker group
   user:
     name: "{{ username }}"
     group: docker


 - name: Add an apt signing key for Kubernetes
   apt_key:
     url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
     state: present

 - name: Adding apt repository for Kubernetes
   apt_repository:
     repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
     state: present
     filename: kubernetes.list

 - name: Install Kubernetes binaries
   apt: 
     name: "{{ packages }}"
     state: present
     update_cache: yes
   vars:
     packages:
       - kubelet 
       - kubeadm 
       - kubectl
       - nfs-common
      

 - name: Restart kubelet
   service:
     name: kubelet
     daemon_reload: yes
     state: restarted
